spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Set to update if you want Spring to create the tables automatically
    show-sql: false  # Set to true if you want to see the SQL statements in the logs
    database-platform: org.hibernate.dialect.PostgreSQLDialect
